config/routes.rb
Rails.application.routes.draw do
  get 'chart/index'
  get 'home', to: 'home#index'
  get 'dashboard', to: 'work_packages#dashboard'
  get 'relatorio', to: 'work_packages#relatorio'
  get 'search', to: 'work_packages#search'
  get 'chart/index'

  resources :work_packages

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  self.table_name = 'categories'
  self.primary_key = 'id'

  has_many :work_packages, foreign_key: 'category_id'
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = 'users'
  self.primary_key = 'id'

  has_many :work_packages, foreign_key: 'responsible_id'
end

app/models/work_package.rb
class WorkPackage < ApplicationRecord
  self.table_name = 'work_packages'
  self.primary_key = 'id'

  # Associação para responsável
  belongs_to :responsible_user, class_name: 'User', foreign_key: 'responsible_id', optional: true
  # Associação para as tuplas filhas
  has_many :children, class_name: "WorkPackage", foreign_key: "parent_id"

  # Associacao para categorias:
  belongs_to :category, class_name: 'Category', foreign_key: 'category_id', optional: true

  # Definindo o escopo padrão para filtrar por project_id
  default_scope { where(project_id: 8).where(type_id: [8, 9]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/work_packages_controller.rb
class WorkPackagesController < ApplicationController
  before_action :set_work_package, only: %i[show]

  def index
    @work_packages = WorkPackage.where(parent_id: nil).includes(:children).order(:id)
  end

  def show
    @work_packages_filhos = WorkPackage.where(parent_id: params[:id])
  end

  def dashboard
    @activities = WorkPackage.where(type_id: 8).includes(:category)

    # Calculando a contagem de atividades por categoria (nome)
    @activities_by_category_name = @activities.joins(:category).group('categories.name').count

    # Calculando a média de progresso por categoria (nome)
    @progress_by_category_name = @activities.joins(:category).group('categories.name').average(:done_ratio)

    # Convertendo os dados para um formato adequado para o JavaScript
    @activities_data = @activities.includes(:category).group_by { |activity| activity.category.name }
                                  .transform_values { |activities| activities.map { |activity| { name: activity.subject, completion: activity.done_ratio } } }
                                  .to_json
    Rails.logger.debug "Activities data: #{@activities_data.inspect}"
  end


  def relatorio
    @work_packages_graduacao = WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "GR.%").count
    @work_packages_pos = WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "PG.%").count
    @work_packages_relacoes = WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "REC.%").count
    @work_packages_infra = WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "INFRA.%").count
    @work_packages_gestao = WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "GT.%").count
    @work_packages_processos = WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "GTP.%").count
    @work_packages_servidores = WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "SV.%").count
    @work_packages_discentes= WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "DI.%").count
    @work_packages_comunidade= WorkPackage.where("subject LIKE ? AND parent_id IS NULL", "CA.%").count
    @work_packages_total = WorkPackage.where(parent_id:nil).count

  end

  def search
    @query = params[:query]
    @filter = params[:filter]

    # Lógica para buscar atividades com base nos parâmetros
    @work_packages = WorkPackage.where(type_id:8)

    if @query.present?
      @work_packages = @work_packages.where("subject ILIKE ?", "%#{@query}%")
    end

    if @filter.present?
      case @filter
      when "Graduação"
        @work_packages = @work_packages.where("subject LIKE ?", "GR.%")
      when "Pesquisa e Pós-Graduação"
        @work_packages = @work_packages.where("subject LIKE ?", "PG.%")
      when "Relações Empresariais e Comunitárias"
        @work_packages = @work_packages.where("subject LIKE ?", "REC.%")
      when "Implementações e Infraestrutura"
        @work_packages = @work_packages.where("subject LIKE ?", "INFRA.%")
      when "Gestão do Campus"
        @work_packages = @work_packages.where("subject LIKE ?", "GT.%")
      when "Processos"
        @work_packages = @work_packages.where("subject LIKE ?", "GTP.%")
      when "Servidores"
        @work_packages = @work_packages.where("subject LIKE ?", "SV.%")
      when "Discentes"
        @work_packages = @work_packages.where("subject LIKE ?", "DI.%")
      when "Comunidade Acadêmica"
        @work_packages = @work_packages.where("subject LIKE ?", "CA.%")
      else
        @work_packages = @work_packages
      end
    end
    @work_packages = @work_packages.order(:id)
  end

  private

  def set_work_package
    @work_package = WorkPackage.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/work_packages_helper.rb
module WorkPackagesHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag "home" %>
<%= image_tag 'utfprfundo.png', class: 'background-image' %>
<div class="content">
    <div class="background-overlay"></div>
        <div class="content-container">
            <div class="texto">
                <h1>Planejamento Participativo</h1>
                <h2> 
                    Navegue pelo nosso site para descobrir os projetos em desenvolvimento,
                    metas e objetivos da UTFPR Campus Pato Branco
                    <br><br>
                    Para saber mais sobre o campus acesse: <br><a href="https://www.utfpr.edu.br/campus/patobranco">UTFPR Pato Branco</a>
        </div>
                </h2>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar" %>

<nav class="navbar">

    <%= link_to image_tag("logo-utfpr.png", class:"logo"), root_path %>

    <ul id="activities-links">
        <li><%= link_to "Objetivos", work_packages_path, class: current_page?(work_packages_path) ? 'active' : nil %></li>
        <li><%= link_to "Dashboards", dashboard_path, data: { turbo: "false" }, class: current_page?(dashboard_path) ? 'active' : nil %>
        <li><%= link_to "Relatórios", relatorio_path, class: current_page?(relatorio_path) ? 'active' : nil%>
</li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planejamento Participativo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <%= favicon_link_tag 'imagesfavicon.png' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%
=begin%>
 <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
<%
=end%>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/chart.js' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <%= yield %>

    
  </body>
</html>

app/views/work_packages/_chart.html.erb
<%= stylesheet_link_tag "chart" %>


<div class="chart-container" style="width: 100%; overflow-x: auto; display: flex;">
  <div class="legend-container" id="legend_<%= work_package.id %>" style="width: 30%; flex-shrink: 0;">
    <!-- Aqui é onde a legenda será renderizada dinamicamente -->
  </div>
  <div class="chart" style="flex-grow: 1;">
    <canvas id="barChart_<%= work_package.id %>" style="height: 400px;"></canvas> <!-- Definindo a altura do canvas -->
  </div>
</div>

<script>
  var data_<%= work_package.id %> = [ //Work_package pai
    <% work_package.children.each do |child| %>
      { subject: '<%= child.subject.strip.gsub(/\s+/, ' ').gsub("'", "\\\\'") %>', done_ratio: <%if child.done_ratio == 0 %> <%= 1 %> <%else%> <%= child.done_ratio %> <%end%>}, //para mostrar o progresso 0 também
    <% end %>
  ];

var aux = 133;// para ajudar a gerar cores distintas

var ctx_<%= work_package.id %> = document.getElementById('barChart_<%= work_package.id %>').getContext('2d');
var barChart_<%= work_package.id %> = new Chart(ctx_<%= work_package.id %>, {
    type: 'bar',
    data: {
      labels: data_<%= work_package.id %>.map(item => item.subject),
      datasets: [{
        label: 'Progresso',
        data: data_<%= work_package.id %>.map(item => item.done_ratio),
        backgroundColor: data_<%= work_package.id %>.map(item => randomColor()), // Usando cores aleatórias para as barras
        borderWidth: 2,
      }]
    },
    options: {
      maintainAspectRatio: false,
      scales: {
        x: {
          display: false // Oculta os rótulos do eixo X
        },
        y: {
          display: true,
          min: 0, //escala de y
          max: 100
        }
      }
    }
});


  // Gerando a legenda dinamicamente
  var legend_<%= work_package.id %> = document.getElementById('legend_<%= work_package.id %>');
  data_<%= work_package.id %>.forEach(function(item, index) {
    var legendItem = document.createElement('div');
    legendItem.classList.add('legend-item');

    var colorBox = document.createElement('div');
    colorBox.classList.add('legend-color');
    colorBox.style.backgroundColor = barChart_<%= work_package.id %>.data.datasets[0].backgroundColor[index];
    legendItem.appendChild(colorBox);

    var text = document.createElement('span');
    text.textContent = item.subject;
    legendItem.appendChild(text);

    legend_<%= work_package.id %>.appendChild(legendItem);
  });


function randomColor() {
  var h = aux;
  aux = (h + 133) % 360
  var s = 100; 
  var l = 50; 
  var a = 0.4; // transparência em 0.4

  return 'hsla(' + h + ', ' + s + '%, ' + l + '%, ' + a + ')';
}
</script>

app/views/work_packages/_searchbar.html.erb
<%= stylesheet_link_tag "activity" %>

<div class=search-bar>
        <%= form_tag search_path, method: :get do %>
            Nome do Objetivo:
            <%= text_field_tag :query, params[:query], placeholder: "Opcional"%>   
            Dimensão:     
            <%= select_tag :filter, options_for_select(["Todos", "Graduação", "Pesquisa e Pós-Graduação", "Relações Empresariais e Comunitárias", "Implementações e Infraestrutura", "Gestão do Campus", "Processos", "Servidores","Discentes", "Comunidade Acadêmica"], params[:filter]), class: "form-control" %>         
          <%= submit_tag "Buscar", class: "btn btn-primary" %>
      <% end %>
      </div>

app/views/work_packages/_work_package.html.erb
<%= stylesheet_link_tag "activity" %>


<div class="work_package">
  <p>
    <strong>Nome:</strong>
    <%= work_package.subject %>
  </p>

  <% if work_package.parent_id.nil? %>
  <p>
    <strong>Dimensão:</strong>
    
    <% if work_package.subject =~ /^GR\./ %>
      Graduação
    <% elsif work_package.subject =~ /^PG\./ %>
      Pesquisa e Pós-Graduação
    <% elsif work_package.subject =~ /^REC\./ %>
      Relações Empresariais e Comunitárias
    <% elsif work_package.subject =~ /^INFRA\./ %>
      Infraestrutura
    <% elsif work_package.subject =~ /^GT\./ %>
      Gestão do Campus
    <% elsif work_package.subject =~ /^GTP\./ %>
      Processos
    <% elsif work_package.subject =~ /^SV\./ %>
      Servidores
    <% elsif work_package.subject =~ /^CA\./ %>
      Comunidade Acadêmica
    <% end %>
  </p>
<% end %>


  <p>
  <% if work_package.parent_id.present? %>
    <strong>Responsável:</strong>
    <% if work_package.responsible_user.present? %>
      <%= work_package.responsible_user.firstname %> <%= work_package.responsible_user.lastname %>
    <% else %>
      Não atribuído
    <% end %>
  <% end %>
</p>

  <p>
    <strong>Progresso:</strong>
    <span class="progress-container">
      <span class="progress-bar" style="width: <%= work_package.done_ratio  %>%;"></span>
      <span class="progress-label"><%= work_package.done_ratio %>%</span>
    </span>
  </p>

  <% if action_name == "show" && work_package.id.to_s == params[:id].to_s%>
    <p>
      <strong>Descrição:</strong>
      <%= simple_format(work_package.description) %>
    </p>
  <% end %>

</div>

app/views/work_packages/dashboard.html.erb
<%= stylesheet_link_tag "dashboard" %>

<div id="container">
    <div class="row">

        <div class="chart-container completion">
            <h3>Percentual de conclusão </h3>
            <canvas id="completionChart" ></canvas>
        </div>

    
        <div class="chart-container radar">
            <h3>Evolução</h3>
            <canvas id="radarChart"></canvas>
        </div>

        <div class="chart-container bola">
            <h3>Distribuição de Dimensões</h3>
            <canvas id="activityChart" ></canvas>
        </div>

    </div>
</div>

<script>
let activities = <%= @activities_data.html_safe %>;

let activityChart = null;
let completionChart = null;
let radarChart = null; 

document.addEventListener('DOMContentLoaded', function() {
    updateCharts();
});

function generatePastelColors(numColors) {
    const colors = [];
    for (let i = 0; i < numColors; i++) {
        colors.push(generateRandomPastelColor(colors));
    }
    return colors;
}

var h = 0; 
function generateRandomPastelColor() {
    h += 133; 
    h = h % 360;
    return 'hsla(' + h + ', 100%, 50%, 0.4)'; // 0.4 é a transparência
}

function updateCharts() {
    if (activityChart !== null) {
        activityChart.destroy();
    }
    if (completionChart !== null) {
        completionChart.destroy();
    }
    if (radarChart !== null) {
        radarChart.destroy();
    }

    const activityLabels = Object.keys(activities);
    const numActivities = activityLabels.length;
    const activityColors = generatePastelColors(numActivities);
    
    const activityData = activityLabels.map(categoryName => activities[categoryName].length);

    const activityChartCtx = document.getElementById('activityChart').getContext('2d');
    activityChart = new Chart(activityChartCtx, {
        type: 'doughnut',
        data: {
            labels: activityLabels,
            datasets: [{
                label: 'Objetivos',
                data: activityData,
                backgroundColor: activityColors,
                borderWidth: 1,
                hoverOffset: 15
            }]
        },
        options: {
            plugins: {
                legend: {
                    position: 'bottom' // Define a posição da legenda como 'bottom' (embaixo)
                }
            }
        }
    });

    const completionData = activityLabels.map(categoryName => {
        const total = activities[categoryName].reduce((acc, activity) => acc + activity.completion, 0);
        const averageCompletion = activities[categoryName].length > 0 ? total / activities[categoryName].length : 0;
        return averageCompletion === 0 ? 0.3 : averageCompletion;
    });
    console.log(completionData);

    const completionChartCtx = document.getElementById('completionChart').getContext('2d');
    completionChart = new Chart(completionChartCtx, {
        type: 'bar',
        data: {
            labels: activityLabels,
            datasets: [{
                label: 'Média de Conclusão',
                data: completionData,
                backgroundColor: activityColors,
                borderColor: 'rgba(0, 0, 0, 0.2)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });

    // Criando o Radar Chart
    const radarData = { 
        labels: activityLabels,
        datasets: [
            {
                label: 'Progresso',
                data: completionData,
                backgroundColor: 'rgba(54, 162, 235, 0.2)', 
                borderColor: 'rgba(54, 162, 235, 1)', 
                borderWidth: 1
            }
        ]
    };

    const radarChartCtx = document.getElementById('radarChart').getContext('2d');
    radarChart = new Chart(radarChartCtx, {
        type: 'radar',
        data: radarData,
        options: {
            scales: {
                r: {
                    suggestedMin: 0,
                    suggestedMax: 100, // Ajuste a escala se necessário
                    pointLabels: {
                        font: {
                            size: 11 // Tamanho da fonte para os rótulos dos pontos
                        }
                    }
                }
            }
        }
    });
}
</script>

app/views/work_packages/index.html.erb
<%= stylesheet_link_tag 'activity' %>

  <div class="background"></div>

      <%= render "searchbar" %>

      <div class="activities">

        <% @work_packages.each do |work_package| %>
          <div class="activity">  
             <%= render work_package %>
             <p id="detalhes">
              <%= link_to "Detalhes", work_package %>
             </p>
          </div>

          <%= render "chart", work_package: work_package %>

        <% end %>
      </div>

  </div>

app/views/work_packages/relatorio.html.erb
<%= stylesheet_link_tag "relatorio" %>

<div class="report-container">
    <h2 class="report-title">Dimensões</h2> 

    <h3 class="activity-list"> 
        <ul>
        <li>Graduação: <%=@work_packages_graduacao%></li>
        <li>Pesquisa e Pós-Graduação: <%=@work_packages_pos%></li>
        <li>Infraestrutura: <%=@work_packages_infra%></li>
        <li>Relações Empresariais e Comunitárias: <%=@work_packages_relacoes%></li>
        <li>Gestão do Campus: <%=@work_packages_gestao%></li>
        <li>Servidores: <%=@work_packages_servidores%></li>
        <li>Processos: <%=@work_packages_processos%></li>
        <li>Discentes: <%=@work_packages_discentes%></li>
        <li>Comunidade Acadêmica: <%=@work_packages_comunidade %></li>
        </ul>
    </h3>

    <h3>Total: <span class="total-value"><%=@work_packages_total%></span></h3>

app/views/work_packages/search.html.erb
<%= stylesheet_link_tag "activity" %>

<div class="background"></div>

  <%= render "searchbar" %>

  <div class="activities">

    <% if @work_packages.present? %>

        <% @work_packages.each do |work_package| %>
          <div class="activity">
            <%= render work_package %>
            <p id="detalhes">
              <%= link_to "Detalhes", work_package %>
            </p>
          </div>
          <%= render "chart", work_package: work_package %>
        <% end %>
    <% else %>
      <p>Nenhuma atividade encontrada.</p>
    <% end %>
</div>

app/views/work_packages/show.html.erb
<%= stylesheet_link_tag "activity" %>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


<%if @work_package.parent_id.present?%>
  <%= link_to 'Voltar para Objetivo', work_package_path(@work_package.parent_id), class: 'voltar'  %>
<%elsif%>
  <%= link_to 'Voltar para Objetivos', work_packages_path, class: 'voltar'%>
<%end%>

<div class="activities">
  
  <div class="activity">
    <%= render @work_package %>
  </div>
  <% @work_packages_filhos.each do |work_package| %>
      <div class="activity">
          <%= render work_package %>
        <p id="detalhes">
          <%= link_to "Detalhes", work_package %>
        </p>
      </div>
    <% end %>
</div>